### ISSUE TITLE
Backlog v.0.0.1

### ISSUE THREAD

**Issue by nardil** [link-it/govpay-portal#1]
- [x] Nell'archivio dei pagamenti tutte le entry, ad eccezione dei rifiutati e dei pagamenti in corso, devono prevedere il download della ricevuta.
- [x] La lista della posizione debitoria deve essere acquisita fornendo anche il parametro "ordinamento=smart"
- [x] Quando scade la sessione, se continuo a navigare ricevo un 401 e mi compare un messaggio "Richiesta non autorizzata: Sessione Scaduta" e le liste mi compaiono vuote. Dovrebbe tornare alla home per il login. Serve forse un 403 per avere questo comportamento?
- [x] Il messaggio di errore "Richiesta non autorizzata: Sessione Scaduta" non entra nel popup
- [x] Nella vista a mobile, se la scritta nell'header non entra, deve ridursi il font ed andare eventualmente su piu' linee per entrare (vedi www.governo.it)
- [x] quando scorro in giu, l'header dovrebbe ridursi per far spazio ai contenuti (vedi www.governo.it)
- [x] Pagando in forma anonima, al termine del pagamento non c'e' modo di tornare alla home
- [x] Dopo il login si dovrebbe atterrare direttamente sulla pagina della posizione debitoria
- [x] Nella posizione debitoria, le pendenze scadute non devono avere icone

**Comment by simo-git** [comment]
- [x]  Nell'archivio dei pagamenti tutte le entry, ad eccezione dei rifiutati e dei pagamenti in corso, devono prevedere il download della ricevuta.
- [x] La lista della posizione debitoria deve essere acquisita fornendo anche il parametro "ordinamento=smart"
- [x] Quando scade la sessione, se continuo a navigare ricevo un 401 e mi compare un messaggio "Richiesta non autorizzata: Sessione Scaduta" e le liste mi compaiono vuote. Dovrebbe tornare alla home per il login. Serve forse un 403 per avere questo comportamento?
- [x] Il messaggio di errore "Richiesta non autorizzata: Sessione Scaduta" non entra nel popup
- [x] Nella vista a mobile, se la scritta nell'header non entra, deve ridursi il font ed andare eventualmente su piu' linee per entrare (vedi www.governo.it)
- [x] quando scorro in giu, l'header dovrebbe ridursi per far spazio ai contenuti (vedi www.governo.it)
- [x] Pagando in forma anonima, al termine del pagamento non c'e' modo di tornare alla home
- [x] Dopo il login si dovrebbe atterrare direttamente sulla pagina della posizione debitoria
- [x] Nella posizione debitoria, le pendenze scadute non devono avere icone
