### ISSUE TITLE
URL di ritorno malformata in portale multitenant

### ISSUE THREAD

**Issue by nardil** [link-it/govpay-portal#19]
La url di ritorno indicata nella richiesta di pagamento e' malformata.
Nella query string viene inserito questo il parametro in questo modo: `?@00321080384` ma manca l'uguale  `?@=00321080384`

**Comment by simo-git** [comment]
Hai controllato se il parametro "PAY_RESPONSE_URL" nel file di configurazione è formalmente corretto?

**Comment by nardil** [comment]
Si, errore mio di configurazione. Era sbagliato il parametro.
