### ISSUE TITLE
Revisione portale 4.0

### ISSUE THREAD

**Issue by atatarelli** [link-it/govpay-portal#53]
- [x] Il reCaptcha non viene caricato.
- [x] ~~Nel menu/sidebar Il logo e il nome dell'ente vanno ingranditi e proporzionati al titolo. C'è un max-width che potrebbe essere aumentato.~~
- [x] ~~Togliere il padding al logo nell'header dell'applicazione.~~
- [x] Non funziona il link diretto al servizio/pendenza.
- [x] Dettaglio Servizio - Eliminare l'effetto del "mouseover" sulla label delle properties.
![image](https://user-images.githubusercontent.com/35455716/127174172-2442990c-b934-4800-a113-871a6bf03c51.png)
- [x] Dettaglio Servizio - Formattazione campo "Descrizione". Trovare una soluzione per permettere l'inserimento di alcuni tag markdown (formattazione testo, elenco puntato?, link, accapo) nel file json.
- [x] Menu - Eliminare la visualizzazione automatica della sidebar quando lo schermo è "min-width: 1600px". Il menu deve essere aperto solo tramite pulsante menu (icona hamburger).
- [x] Sito statico - Rivedere header pagina help online.

**Comment by nardil** [comment]
Per il link diretto, la sintassi corretta e' la seguente: `/dettaglio-servizio/<idDominio>/<idTipoPendenza>`

**Comment by atatarelli** [comment]
- [ ] Dettaglio servizio - Quando il "titolo" è troppo lungo il pulsante accedi si riduce in modo non corretto. Ridurre la lunghezza dei titolo per evitare questa situazione.
![image](https://user-images.githubusercontent.com/35455716/127191671-0219a0d6-1f01-4a40-8a85-4e0bb034e5cf.png)
