### ISSUE TITLE
Configurazione pagamenti Spontanei su govpay-portal

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay-portal#64]
Ciao vorrei provare ad attivare i pagamenti spontanei (uso già senza problemi pagamenti online precaricati su Govpay), ma non riesco a capire bene quale sia la procedura corretta per farlo.

Ho giusto fatto una prova: 
- abilitando pagamento spontaneo su una pendenza di prova
- abilitando pagamento spontaneo su un ente per la stessa pendenza sopra indicata

ma lato govpay-portal non vedo cambiamenti.

Cosa manca?

Grazie mille in anticipo!

**Comment by nardil** [comment]
Duplicato di https://github.com/link-it/govpay/issues/446
